require('dotenv').config();
const express=require('express'), path=require('path'), crypto=require('crypto'), Database=require('better-sqlite3');
const app=express();
const PORT=Number(process.env.PORT||3000);
const BASE_URL=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,'');
const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';
const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const META_VERIFY_TOKEN=process.env.META_VERIFY_TOKEN||'nexus-verify';
const META_APP_ID=process.env.META_APP_ID||'', META_APP_SECRET=process.env.META_APP_SECRET||'';
const META_REDIRECT_URI=process.env.META_REDIRECT_URI||`${BASE_URL}/api/meta/callback`;
const META_GRAPH_VERSION=process.env.META_GRAPH_VERSION||'v23.0';
const db=new Database(process.env.DB_PATH||'nexus.db'); db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,job TEXT,agent_name TEXT,business TEXT,channel TEXT,tone TEXT,knowledge TEXT,escalation TEXT,actions_json TEXT,system_prompt TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id INTEGER,external_id TEXT,direction TEXT,message TEXT,response TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS business_sources(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id INTEGER,url TEXT,source_type TEXT,raw_text TEXT,knowledge_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS channel_connections(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id INTEGER,channel TEXT,external_account_id TEXT,access_token TEXT,meta_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
app.use(express.json({limit:'4mb'})); app.use(express.urlencoded({extended:true})); app.use(express.static(path.join(__dirname,'public')));
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const JOBS={sales:{name:'FOLLOWER',summary:'Qualifies new leads, answers approved questions, follows up and escalates high-intent conversations.'},support:{name:'RECEPTION',summary:'Handles common customer questions, follows approved policies and escalates uncertain or sensitive cases.'},booking:{name:'SCHEDULER',summary:'Collects booking details, checks configured rules and prepares or requests a booking action.'},content:{name:'STUDIO',summary:'Turns approved business knowledge into platform-ready content while following the requested tone.'},operations:{name:'ANALYST',summary:'Summarizes operational information, highlights exceptions and prepares human-review actions.'}};
function buildPrompt({business,job,channel,tone,knowledge,escalation,actions}){const j=JOBS[job]||JOBS.sales;return `You are ${j.name}, the AI customer-facing employee for ${business}.\nJOB: ${j.summary}\nCHANNEL: ${channel}\nTONE: ${tone}\nAPPROVED ACTIONS: ${(actions||[]).join(', ')||'Reply to customers'}\nESCALATION: ${escalation}\nBUSINESS KNOWLEDGE:\n${knowledge||'(No verified business knowledge supplied yet.)'}\n\nRULES:\n1. Only use verified business knowledge. Never invent prices, services, availability, policies, addresses, opening hours, guarantees, credentials or other facts.\n2. If the answer is not in verified knowledge, say you do not have that information yet and offer human help.\n3. Answer the customer’s actual question first. Do not talk about being an AI unless asked.\n4. Keep replies natural, concise and channel-appropriate.\n5. Use the customer’s language when possible.\n6. Never request passwords, payment-card numbers, security codes or unnecessary sensitive information.\n7. Do not make irreversible commitments without a configured business rule or human approval.\n8. If the customer shows buying intent, guide them to the next configured action.`}
function upsertCustomer(name,email){const x=db.prepare('SELECT * FROM customers WHERE email=?').get(email);if(x)return x;const r=db.prepare('INSERT INTO customers(name,email) VALUES(?,?)').run(name||'NEXUS Customer',email);return db.prepare('SELECT * FROM customers WHERE id=?').get(r.lastInsertRowid)}
function createAgent(b){const job=JOBS[b.job]?b.job:'sales',prompt=buildPrompt({...b,job});const r=db.prepare('INSERT INTO agents(customer_id,job,agent_name,business,channel,tone,knowledge,escalation,actions_json,system_prompt) VALUES(?,?,?,?,?,?,?,?,?,?)').run(b.customerId||null,job,JOBS[job].name,b.business,b.channel,b.tone,b.knowledge,b.escalation,JSON.stringify(b.actions||[]),prompt);return db.prepare('SELECT * FROM agents WHERE id=?').get(r.lastInsertRowid)}
function normalizeUrl(x){try{const u=new URL(x);if(!/^https?:$/.test(u.protocol))return null;u.hash='';return u.toString()}catch{return null}}
function sourceType(url){const h=new URL(url).hostname.toLowerCase();if(h.includes('instagram.com'))return'Instagram';if(h.includes('facebook.com'))return'Facebook';if(h.includes('whatsapp.com'))return'WhatsApp';return'Website'}
function cleanText(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim()}
function extractHtml(html,url){const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'',desc=(html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([\s\S]*?)["']/i)||[])[1]||'',og=(html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([\s\S]*?)["']/i)||[])[1]||'';const headings=[...html.matchAll(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/gi)].map(x=>cleanText(x[1])).filter(Boolean).slice(0,80),body=cleanText(html).slice(0,30000),links=[...html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(x=>({href:x[1],text:cleanText(x[2])})).filter(x=>x.text).slice(0,100);return{url,title:cleanText(title),description:cleanText(desc),ogTitle:cleanText(og),headings,body,links}}
async function fetchPublicSource(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'user-agent':'NEXUS-Business-Analyzer/1.0'}});return{status:r.status,contentType:r.headers.get('content-type')||'',finalUrl:r.url,text:(await r.text()).slice(0,800000)}}finally{clearTimeout(t)}}
async function answerWithAI(agent,message,channel){if(!OPENAI_API_KEY)return{response:'The AI provider is not configured on this server yet.',live:false};const input=`BUSINESS: ${agent.business}\nCHANNEL: ${channel||agent.channel}\nVERIFIED KNOWLEDGE:\n${agent.knowledge||'(none)'}\n\nCUSTOMER MESSAGE:\n${message}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,instructions:agent.system_prompt,input,max_output_tokens:500})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'OpenAI request failed');const text=d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join(' ').trim();if(!text)throw new Error('AI returned an empty response');return{response:text,live:true,responseId:d.id}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'nexus-ai-engine',aiConfigured:Boolean(OPENAI_API_KEY),metaConfigured:Boolean(META_APP_ID&&META_APP_SECRET),model:OPENAI_MODEL,baseUrl:BASE_URL}));
app.post('/api/business/analyze',async(req,res)=>{const url=normalizeUrl(req.body?.url);if(!url)return res.status(400).json({error:'Enter a valid public http(s) URL.'});try{const f=await fetchPublicSource(url);if(f.status>=400)return res.status(502).json({error:`Source returned HTTP ${f.status}.`});const p=extractHtml(f.text,f.finalUrl||url);res.json({ok:true,source:sourceType(url),fetchStatus:f.status,contentType:f.contentType,finalUrl:f.finalUrl||url,knowledge:{sourceType:sourceType(url),sourceUrl:f.finalUrl||url,businessName:p.ogTitle||p.title||new URL(url).hostname,description:p.description,headings:p.headings,pageText:p.body,usefulLinks:p.links.filter(x=>/menu|service|product|price|contact|location|about|book|shop|faq|hours/i.test(x.text+' '+x.href)).slice(0,40)}})}catch(e){res.status(502).json({error:'Could not read that public source.'})}});
app.post('/api/agent/generate',(req,res)=>{const b=req.body||{};if(!b.business)return res.status(400).json({error:'Business name required'});const c=upsertCustomer(b.name||'NEXUS Customer',b.email||`customer-${crypto.randomUUID()}@nexus.local`);const a=createAgent({customerId:b.customerId||c.id,business:b.business,job:b.job||'sales',channel:b.channel||'Website chat',tone:b.tone||'Professional & friendly',knowledge:b.knowledge||'',escalation:b.escalation||'Ask a human when unsure',actions:Array.isArray(b.actions)?b.actions:[]});res.json({agentId:a.id,agentName:a.agent_name,summary:JOBS[a.job].summary,systemPrompt:a.system_prompt,status:'ready',aiConfigured:Boolean(OPENAI_API_KEY)})});
app.post('/api/agent/chat',async(req,res)=>{const{agentId,message,channel}=req.body||{};if(!agentId||!message)return res.status(400).json({error:'agentId and message required'});const a=db.prepare('SELECT * FROM agents WHERE id=?').get(agentId);if(!a)return res.status(404).json({error:'Agent not found'});try{const r=await answerWithAI(a,message,channel||a.channel);db.prepare('INSERT INTO messages(agent_id,external_id,direction,message,response) VALUES(?,?,?,?,?)').run(a.id,'chat-'+Date.now(),'inbound',message,r.response);res.json(r)}catch(e){res.status(502).json({error:e.message})}});
app.post('/api/channel/inbound',async(req,res)=>{const{agentId,externalId,message,channel,customerRef}=req.body||{};if(!agentId||!message)return res.status(400).json({error:'agentId and message required'});const a=db.prepare('SELECT * FROM agents WHERE id=?').get(agentId);if(!a)return res.status(404).json({error:'Agent not found'});try{const r=await answerWithAI(a,message,channel||a.channel);db.prepare('INSERT INTO messages(agent_id,external_id,direction,message,response) VALUES(?,?,?,?,?)').run(a.id,externalId||'','inbound',message,r.response);res.json({status:'processed',mode:r.live?'live-ai':'engine-ready',agent:a.agent_name,channel:channel||a.channel,response:r.response,customerRef})}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/webhooks/meta',(req,res)=>{if(req.query['hub.mode']==='subscribe'&&req.query['hub.verify_token']===META_VERIFY_TOKEN)return res.status(200).send(req.query['hub.challenge']);res.sendStatus(403)});
const oauthStates=new Map();app.get('/api/meta/connect',(req,res)=>{if(!META_APP_ID||!META_APP_SECRET)return res.status(503).send('Meta OAuth is not configured on this server yet.');const agentId=String(req.query.agentId||'');if(!agentId)return res.status(400).send('agentId is required');const state=crypto.randomBytes(24).toString('hex');oauthStates.set(state,{agentId,expires:Date.now()+600000});const u=new URL(`https://www.facebook.com/${META_GRAPH_VERSION}/dialog/oauth`);u.searchParams.set('client_id',META_APP_ID);u.searchParams.set('redirect_uri',META_REDIRECT_URI);u.searchParams.set('state',state);u.searchParams.set('scope',process.env.META_SCOPE||'instagram_business_basic,instagram_business_manage_messages,pages_show_list,pages_messaging');res.redirect(u.toString())});
app.get('/api/meta/callback',async(req,res)=>{const s=oauthStates.get(String(req.query.state||''));oauthStates.delete(String(req.query.state||''));if(!s||s.expires<Date.now())return res.status(400).send('Invalid or expired OAuth state.');if(!req.query.code)return res.status(400).send('Missing OAuth code.');try{const u=new URL(`https://graph.facebook.com/${META_GRAPH_VERSION}/oauth/access_token`);u.searchParams.set('client_id',META_APP_ID);u.searchParams.set('client_secret',META_APP_SECRET);u.searchParams.set('redirect_uri',META_REDIRECT_URI);u.searchParams.set('code',req.query.code);const r=await fetch(u);const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error?.message||'Meta token exchange failed');db.prepare('INSERT INTO channel_connections(agent_id,channel,external_account_id,access_token,meta_json) VALUES(?,?,?,?,?)').run(s.agentId,'Meta','',d.access_token,JSON.stringify({connectedAt:new Date().toISOString()}));res.send('NEXUS Meta authorization completed. Return to your NEXUS workspace.')}catch(e){res.status(502).send('Meta connection failed: '+e.message)}});
app.listen(PORT,()=>console.log(`NEXUS AI Engine running at ${BASE_URL}`));
